name: CityBuilder
version: 1.0.0
main: com.citybuilder.CityBuilder
api-version: 1.21
author: 7Zeb
description: A Spigot plugin for spawning filler buildings like stores, apartments, warehouses, and skyscrapers.
website: https://github.com/7Zeb/CityBuilder

commands:
  fillerbuilding:
    description: Spawn a filler building at your location
    usage: /fillerbuilding <template>
    permission: citybuilder.filler.build

permissions:
  citybuilder.filler.build:
    description: Allows player to spawn filler buildings
    default: op
